### ISSUE TITLE
Request: Adobe brackets profile

### ISSUE THREAD

**Issue by triceratops1** [chiraag-nataraj/firejail-profiles#1]
Config files
~/.Brackets
/opt/brackets   
~/Documents  (or its name at your language)

**Comment by chiraag-nataraj** [comment]
So, I'm having a problem getting Chrome to run within the sandbox. Currently investigating.

**Comment by chiraag-nataraj** [comment]
If you don't need live preview, I'm pretty much done with the profile. I'll document which things you need to disable should you wish to use live preview.
