### ISSUE TITLE
Request:  amule profile

### ISSUE THREAD

**Issue by triceratops1** [chiraag-nataraj/firejail-profiles#11]
p2p its still popular
but with the increased issues with it (censorship/copyright-censorship)  

would be extremely good have a firejail profile for amule (protecting you from "misfortunes")

best regards

**Comment by chiraag-nataraj** [comment]
Sure, I'll look into it!

**Comment by triceratops1** [comment]
and a viewnior profile :)

**Comment by chiraag-nataraj** [comment]
Added viewnior!

**Comment by chiraag-nataraj** [comment]
@triceratops1 I'm not sure how to test the amule profile (as in I'm not sure what actions are normally taken) since I don't use it. If you can give me some hints on what actions your normally use, I can at least come up with an initial iteration.

**Comment by triceratops1** [comment]
download torrents, movies and files  


generally  i want it to downloads


or at its custom directory (.amule)

**Comment by chiraag-nataraj** [comment]
Okay. I'll make a profile and you can give it a go and let me know if it works ^_^

**Comment by chiraag-nataraj** [comment]
Alright I'll close this for now. Feel free to re-open this issue if the profile doesn't work.
