### ISSUE TITLE
profiles

### ISSUE THREAD

**Issue by triceratops1** [chiraag-nataraj/firejail-profiles#14]
can you give
profiles for these
https://imagej.nih.gov/ij/
http://hugin.sourceforge.net/
https://sourceforge.net/projects/macrofusion/

**Comment by chiraag-nataraj** [comment]
Yup, I'll look into it!

**Comment by chiraag-nataraj** [comment]
Looking at Hugin, I'm having a problem with whitelisting the configuration file as it apparently tries to overwrite the file at startup and can't do that (it thinks the file is in use). Will try to debug the problem.

**Comment by triceratops1** [comment]
can we cut internet for this app (if we can't harden..we kill internet)

**Comment by chiraag-nataraj** [comment]
Yup, I can do that. I'll ignore restricting access to files in the home directory and cut internet (as I was going to do anyway).

**Comment by chiraag-nataraj** [comment]
Added Hugin and ImageJ!

**Comment by triceratops1** [comment]
i've troubles with kdenlive profile 

`whitelist ${HOME}/.config/
whitelist ${HOME}kdenlive

whitelist ${DOWNLOADS}
whitelist ${HOME}/Videos

blacklist /boot
blacklist /media
blacklist /mnt
blacklist /opt

#private-bin kdenlive,kdenlive_render,dbus-launch,melt,ffmpeg,ffplay,ffprobe,dvdauthor,genisoimage,vlc,xinekdeinit5,kshell5kdeinit5_shutdownkdeinit5_wrapperkdeinit4,kshell4kdeinit4_shutdownkdeinit4_wrapper
#private-dev
#private-etc fonts,alternatives,X11,pulse,passwd

whitelist /tmp/.X11-unix
# I have forced DBus to use an ordinary unix socket
whitelist /tmp/dbus_session_socket

#shell none
#seccomp
#caps.drop all
net none
#noroot
#nogroups
# ipc-namespace`

i've gapped ALL.


but blender works without private-bin private-dev
and private-etc

**Comment by chiraag-nataraj** [comment]
Added a macrofusion profile! Let me know if it's not working properly.
