### ISSUE TITLE
blender fail+fix

### ISSUE THREAD

**Issue by triceratops1** [chiraag-nataraj/firejail-profiles#15]
blender doesnt work now

with it
works
https://paste.teknik.io/Raw/Wmkyv

**Comment by chiraag-nataraj** [comment]
Okay. Can you uncomment `private-dev` and see if it still works? If it does, that would point to something I'm not whitelisting in either `private-etc` or `private-bin`.

**Comment by triceratops1** [comment]
it works :)

**Comment by chiraag-nataraj** [comment]
Ah, good. Let's see if it still works with `private-etc` uncommented. If it does, that means that your `blender` needs access to additional binaries that mine does not. Otherwise...not quite sure.

**Comment by triceratops1** [comment]
blender: error while loading shared libraries: libOpenCOLLADAStreamWriter.so: cannot open shared object file: No such file or directory

**Comment by triceratops1** [comment]
but works with private-bin uncommented (just commented private-etc)

**Comment by chiraag-nataraj** [comment]
Huh okay. That's weird. I don't even have that library installed on my system...

**Comment by chiraag-nataraj** [comment]
can you do a `locate libOpenCOLLADAStreamWriter.so` to find where it's located?

**Comment by triceratops1** [comment]
yes

**Comment by chiraag-nataraj** [comment]
Ahh...okay. But still, that should be a library, no? That is, it shouldn't be affected by commenting/uncommenting stuff in /etc.

**Comment by triceratops1** [comment]
its rare :D

**Comment by chiraag-nataraj** [comment]
So I guess my question is: since I don't have Arch (and I don't need opencollada), can you use `firejail --debug` or `firejail --trace` to figure out what files it's trying to access in `/etc`?

**Comment by triceratops1** [comment]
ok

**Comment by triceratops1** [comment]
https://paste.teknik.io/Raw/D1MWN

**Comment by chiraag-nataraj** [comment]
Okay, that didn't really give me anything. Can you comment out `private-etc` and run `firejail --trace blender` so that it loads completely and post the output?

**Comment by triceratops1** [comment]
https://p.teknik.io/pZmWn

**Comment by triceratops1** [comment]
https://p.teknik.io/2wFz8

**Comment by chiraag-nataraj** [comment]
Huh okay. It seems to be accessing `/etc/machine-id` and `/etc/drirc`. If you whitelist those, are you able to run Blender with `private-etc` enabled?

**Comment by triceratops1** [comment]
firejail --trace --profile=blender.profile blender
Reading profile blender.profile
Warning: user namespaces not available in the current kernel.
Parent pid 9657, child pid 9658
Child process initialized
blender: error while loading shared libraries: libOpenCOLLADAStreamWriter.so: cannot open shared object file: No such file or directory

Parent is shutting down, bye...
[hue@lorem nords]$

**Comment by triceratops1** [comment]
private-etc pulse,drirc,openal,xdg,machine-id

**Comment by chiraag-nataraj** [comment]
Can you do a `locate libOpenCOLLADAStreamWriter.so` to see where the library is located? Alternatively, an `ldd /usr/bin/blender` might also help.

**Comment by triceratops1** [comment]
/usr/lib/opencollada/

**Comment by chiraag-nataraj** [comment]
Okay...as expected. Is there anything related to `opencollada` in `/etc`?

**Comment by triceratops1** [comment]
np

**Comment by chiraag-nataraj** [comment]
What. This doesn't make any sense. Why would `private-etc` kill Blender, but _only_ if it's using `opencollada`?

**Comment by triceratops1** [comment]
its rare :P 

i've disabled it

**Comment by chiraag-nataraj** [comment]
Okay. I'm going to go ahead and close the issue for now, but feel free to keep experimenting and let me know if you manage to figure out which file(s) it needs access to!
