### ISSUE TITLE
More profiles  

### ISSUE THREAD

**Issue by nyancat18** [chiraag-nataraj/firejail-profiles#17]
can you make profiles for these apps?

1 brl-cad (a millitary-veteran CAD..but common at civilian enviorments)

2 freecad (a civil-use CAD)

3 dia (an oss alternative to ms visio)

4 fontforge

**Comment by chiraag-nataraj** [comment]
I'll look into it!

**Comment by chiraag-nataraj** [comment]
Holy crap freecad has a lot of dependencies...

**Comment by chiraag-nataraj** [comment]
I swear I'm still doing stuff here - just took a bit of a break! Coming back to fontforge now :grinning:

**Comment by chiraag-nataraj** [comment]
Added fontforge!

**Comment by chiraag-nataraj** [comment]
I'm not going to put all of the aliased profiles here since that would _way_ too many. Instead, I'll put a profile stub and a generator script that should generate the scripts locally for you.

**Comment by chiraag-nataraj** [comment]
Added brl-cad.
