### ISSUE TITLE
Buggy profiles

### ISSUE THREAD

**Issue by triceratops1** [chiraag-nataraj/firejail-profiles#2]
Synfigstudio

> irejail synfigstudio
Reading profile /etc/firejail/synfigstudio.profile
Warning: user namespaces not available in the current kernel.
Parent pid 4557, child pid 4558
Child process initialized

   synfig studio -- starting up application...

** (synfigstudio:7): WARNING **: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-sDCGkevOjL: Conexión rehusada
mlt_repository_init: failed to dlopen /usr/lib/mlt/libmltopengl.so
  (libmovit.so.4: no se puede abrir el fichero del objeto compartido: No existe el fichero o el directorio)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Standard Exception: std::exception
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to open module list file 'synfig_modules.cfg'

Parent is shutting down, bye...

**Comment by chiraag-nataraj** [comment]
Can you do a `locate synfig_modules.cfg` for me? Mine's located at `/etc/synfig/synfig_modules.cfg`, but I guess it may be located in other places in other distros.

**Comment by triceratops1** [comment]
/etc/synfig_modules.cfg

**Comment by chiraag-nataraj** [comment]
Uploaded a revised profile that should take care of this.
