### ISSUE TITLE
signal does not start

### ISSUE THREAD

**Issue by St0ner1995** [chiraag-nataraj/firejail-profiles#22]
hello,

so i have tried to get signal-desktop to start in firejail

by default, signal installs in /opt/Signal and sets up a symlink in /usr/local/bin/signal-desktop -> /opt/Signal/signal-desktop

when i run the command `firejail signal-desktop` all i get in return is

```
~$ firejail signal-desktop
Reading profile /etc/firejail/signal-desktop.profile
Parent pid 4752, child pid 4753
Child process initialized

Parent is shutting down, bye...
```

**Comment by chiraag-nataraj** [comment]
Oh wow, didn't even notice the symlink in `/usr/local/bin`. Just uploaded a version that should fix the issue. Let me know if it doesn't :slightly_smiling_face:

**Comment by St0ner1995** [comment]
just tested it, the issue is resolved.
