### ISSUE TITLE
Steam does not show

### ISSUE THREAD

**Issue by St0ner1995** [chiraag-nataraj/firejail-profiles#23]
Hello,

when i start steam in firejail, i don't see the client anywhere

not even in the icon drawer at the bottom left of the screen, which has dropbox in it (working inside firejail too)

**Comment by chiraag-nataraj** [comment]
The steam profile isn't from my repo 😉 You'll want to head over to [firejail](https://github.com/netblue30/firejail/issues) and file a new issue there.
