### ISSUE TITLE
New profiles       

### ISSUE THREAD

**Issue by triceratops1** [chiraag-nataraj/firejail-profiles#3]
could you provide these profiles?
cinelerra
lmms
gimp
inkscape

**Comment by chiraag-nataraj** [comment]
Added inkscape.

**Comment by chiraag-nataraj** [comment]
So apparently the way `private-bin` works, `lmms` thinks it needs to look for libraries in `/usr/local/lib`, which is obviously not correct. I have disabled `private-bin` currently for this profile for this reason.

**Comment by chiraag-nataraj** [comment]
I'm currently having a little trouble getting Cinelerra running due to library version mismatches. Working on it.

**Comment by triceratops1** [comment]
i found some packages of cinelerra and natron (without register)
https://cinelerra-cv.org/five/pkgs/  

this is a pkgbuild, but this bundle could be used at almost all linux distros  
https://aur.archlinux.org/packages/natron-portable/

**Comment by chiraag-nataraj** [comment]
Yeah, that's the package I used. I'm going to compile from source since that's easiest in this case (I use Debian sid/experimental).
