### ISSUE TITLE
[discussion] discord.profile: Doesn't need access to the entirety of /tmp

### ISSUE THREAD

**Issue by mid-kid** [chiraag-nataraj/firejail-profiles#31]
It'd be nice if there was a way to allow discord to only access /tmp/discord.sock, while leaving the rest of /tmp hidden. Right now, discord.profile ignores the `private-tmp` command, exposing the host's /tmp folder.
I've attempted creating the socket beforehand, and whitelisting it in the discord profile, but it seems discord tries to remove the file on bootup.
To fix this, we'd need to either:
- Modify discord itself to not remove the file (the "base" client doesn't update very often so this might be feasible, but I'm not sure if this is even possible due to how sockets work)
- Allow the file to be removed and re-created, without compromising the entirety of /tmp (don't think this is possible due to the way firejail works)
- Have firejail ignore the unlink syscall, so the program thinks it's "unlinked" the file successfully (requires an update to firejail itself)

I'm opening this issue mostly to open dialogue about this, since there's more applications that do similar things, and you might want to be able to communicate with them over sockets outside of the sandbox, or somehow share the same tmpfs mount. Are there any more possible options for doing such a thing?

**Comment by chiraag-nataraj** [comment]
> It'd be nice if there was a way to allow discord to only access /tmp/discord.sock, while leaving the rest of /tmp hidden. Right now, discord.profile ignores the private-tmp command, exposing the host's /tmp folder.

Actually, I just found that removing `ignore private-tmp` seems to let `discord` work just fine. I'll tenatively comment out that line and mark this as solved, but let me know if it breaks on your end (it seems to work just fine on mine).

**Comment by chiraag-nataraj** [comment]
Also, the `whitelist` lines mean that it _only_ has access to `/tmp/.X11-unix` and `/tmp/user/1000`. Not the best, but not exactly the worst either. As you said, it's not really possible right now to deal with this since `discord` doesn't support passing an existing socket (otherwise, writing a wrapper script would be easy).

**Comment by chiraag-nataraj** [comment]
Ooh! One way around this is to do the following:
1. Make a directory `/tmp/user/1000/discord1000`
2. Pass `TMPDIR=/tmp/user/1000/discord1000` as an environment variable.
3. Make sure that directory is whitelisted in your `firejail` profile.
4. Now it should be able to do this without needing access to anything else!

Off to try this now.

**Comment by mid-kid** [comment]
That's a perfect solution. Thanks!
