### ISSUE TITLE
New profile: darktable

### ISSUE THREAD

**Issue by triceratops1** [chiraag-nataraj/firejail-profiles#6]
Darktable
https://gist.github.com/triceratops1/14ae961633898d50df0123bb32c3f490

Shotcut
https://gist.github.com/triceratops1/464d766db8efcae72735d4e4cdfda688

Zart: A GMIC-based webcam manipu
https://gist.github.com/triceratops1/86e85465358d6fdbe4d1f216008cb28d
https://github.com/dtschump/gmic-community/tree/master/zart

**Comment by chiraag-nataraj** [comment]
Oh man! I was already working on Darktable and Shotcut, so I just used mine for that. I will include your Zart profile! Thanks! :)
