### ISSUE TITLE
Enhancement: New profiles

### ISSUE THREAD

**Issue by triceratops1** [chiraag-nataraj/firejail-profiles#7]
1 Ricochet: a torified chat app, simmilar to tox, 
https://ricochet.im/

2 Tbb, the tor browser bundle itself   

http://www.webupd8.org/2013/12/tor-browser-bundle-ubuntu-ppa.html

**Comment by chiraag-nataraj** [comment]
Working on it :)

**Comment by chiraag-nataraj** [comment]
Do you have a ricochet address that I can use to test stuff? I'm not sure if additional things are needed for adding contacts and chatting and such. You can email me at `chiraag.nataraj@gmail.com` if you don't want to post it publicly.

**Comment by chiraag-nataraj** [comment]
Added a tentative Ricochet profile - let me know if it works!

**Comment by chiraag-nataraj** [comment]
@triceratops1 how exactly are you running tbb? Are you installing it? Are you running it from some directory?

**Comment by chiraag-nataraj** [comment]
There's a `torbrowser-launcher` package in Debian, but I have no idea if you're using something similar or if you're downloading the self-contained one directly from the Tor website.

**Comment by chiraag-nataraj** [comment]
Okay, I added a tentative profile for tbb as supported through the `torbrowser-launcher` package in Debian. Let me know if it works, if it breaks, etc. For now, I'm going to go ahead and close this issue, but feel free to reopen it.
