### ISSUE TITLE
What's the OS/architecture?

### ISSUE THREAD

**Issue by mindstormer12** [chiraag-nataraj/firejail-profiles#9]
What's the OS/architecture the profiles were designed for? Latest version of Arch Linux 64-bit? Would be nice to include this information in the README.

**Comment by chiraag-nataraj** [comment]
👍 I designed these on Debian sid/experimental x86_64. I added this information to the README.

**Comment by triceratops1** [comment]
@chiraag-nataraj  i'm using arch

and ALL profiles work

:)

**Comment by chiraag-nataraj** [comment]
☺
